export const exercises = [
  {
    id: 'tall-kneeling-halo',
    name: 'Tall-kneeling halo',
    prescription: '5 / direction',
    mode: 'reps',
    cue: 'Circle close around your head while keeping your ribs down and neck relaxed.',
    tags: ['Shoulder mobility', 'Upper back'],
    media: '/media/tall-kneeling-halo.gif',
    source: 'https://www.youtube.com/watch?v=0esYCS6dFQk',
  },
  {
    id: 'tall-kneeling-chop',
    name: 'Tall-kneeling chop',
    prescription: '6–8 / side',
    mode: 'reps',
    cue: 'Move the bell diagonally across your body. Rotate through your upper back while keeping your hips controlled.',
    tags: ['Rotation', 'Obliques'],
    media: '/media/tall-kneeling-chop.gif',
    source: 'https://www.youtube.com/watch?v=BslVJKQXlcQ',
  },
  {
    id: 'half-kneeling-rotational-press',
    name: 'Half-kneeling rotational press',
    prescription: '6 / side',
    mode: 'reps',
    cue: 'Start light. Rotate smoothly through your torso and finish with the bell controlled overhead—never force the range.',
    tags: ['Shoulders', 'Rotation'],
    media: '/media/half-kneeling-rotational-press.gif',
    source: 'https://www.youtube.com/watch?v=9tbeLypLKHg',
  },
  {
    id: 'kettlebell-windmill',
    name: 'Kettlebell windmill',
    prescription: '5–6 / side',
    mode: 'reps',
    cue: 'Hold the bell overhead with a locked arm. Push your hip sideways, keep a long spine and watch the bell.',
    tags: ['Rotation', 'Shoulder stability'],
    media: '/media/kettlebell-windmill.gif',
    source: 'https://www.youtube.com/watch?v=MP9GRrr18Yc',
  },
  {
    id: 'figure-eight-to-hold',
    name: 'Figure-eight to hold',
    prescription: '6 / direction',
    mode: 'reps',
    cue: 'Pass the bell behind one leg and receive it securely at chest height. Stay smooth rather than rushing.',
    tags: ['Coordination', 'Rotation'],
    media: '/media/figure-eight-to-hold.gif',
    source: 'https://www.youtube.com/watch?v=ukc7kuFBlGY',
  },
  {
    id: 'around-the-body-pass',
    name: 'Around-the-body pass',
    prescription: '10 reps / direction',
    mode: 'reps',
    cue: 'Pass the bell close around your body, receive it at shoulder height and pause before the next circle.',
    tags: ['Shoulders', 'Anti-rotation'],
    media: '/media/around-the-body-pass.gif',
    source: 'https://www.youtube.com/watch?v=nj26JAvAl-U',
  },
]

export const adHocExercises = [
  {
    id: 'pushups',
    name: 'Pushups',
    prescription: 'Reps as desired',
    mode: 'reps',
    cue: 'Keep your body rigid and lower under control.',
    tags: ['Chest', 'Shoulders', 'Triceps'],
    media: '',
    source: '',
  },
]

export const workouts = [
  {
    id: 'workout-b',
    label: 'B',
    name: 'Rotation & resilient shoulders',
    note: 'Complete 2–3 controlled rounds. Accuracy matters more than speed.',
    exerciseIds: exercises.map(({ id }) => id),
  },
]
