export const exercises = [
  {
    id: 'supported-one-arm-row',
    name: 'Supported one-arm row',
    prescription: '8–12 / side',
    mode: 'reps',
    cue: 'Brace your free hand on a sturdy surface. Pull toward your hip and pause for two seconds at the top.',
    tags: ['Upper back', 'Lats'],
    media: '/media/supported-one-arm-row.gif',
    source: 'https://www.youtube.com/watch?v=mt7j2azpbKg',
  },
  {
    id: 'floor-kettlebell-pullover',
    name: 'Floor kettlebell pullover',
    prescription: '8–12 reps',
    mode: 'reps',
    cue: 'Keep your ribs down. Only lower the bell as far as you can without arching your lower back.',
    tags: ['Lats', 'Shoulders'],
    media: '/media/floor-kettlebell-pullover.gif',
    source: 'https://www.youtube.com/watch?v=ZDwGVX0w7k4',
  },
  {
    id: 'half-kneeling-strict-press',
    name: 'Half-kneeling strict press',
    prescription: '5–8 / side',
    mode: 'reps',
    cue: 'Squeeze the bell firmly, keep your ribs stacked over your pelvis and press without leaning sideways.',
    tags: ['Shoulders', 'Core control'],
    media: '/media/half-kneeling-strict-press.gif',
    source: 'https://www.youtube.com/watch?v=wlAJN3GzJWA',
  },
  {
    id: 'bottoms-up-press',
    name: 'Bottoms-up press',
    prescription: '5–8 / side',
    mode: 'reps',
    cue: 'Use a light bell. Crush the handle, keep your wrist vertical and press without letting the bell tip.',
    tags: ['Shoulder stability', 'Grip'],
    media: '/media/bottoms-up-press.gif',
    source: 'https://www.youtube.com/watch?v=UCkeocW0BdI',
  },
  {
    id: 'kettlebell-arm-bar',
    name: 'Kettlebell arm bar',
    prescription: '3 slow reps / side',
    mode: 'reps',
    cue: 'Move slowly and keep the loaded arm vertical. Treat it as controlled shoulder practice, not an aggressive stretch.',
    tags: ['Shoulder control', 'Thoracic rotation'],
    media: '/media/kettlebell-arm-bar.gif',
    source: 'https://www.youtube.com/watch?v=4Ll2Q_vwEG8',
  },
  {
    id: 'suitcase-carry-or-march',
    name: 'Suitcase carry or march',
    prescription: '30–45 sec / side',
    mode: 'duration',
    targetDuration: 30,
    cue: 'Stand tall without leaning away from the bell. Walk slowly, or march in place if space is limited.',
    tags: ['Grip', 'Anti-rotation'],
    media: '/media/suitcase-carry-or-march.gif',
    source: 'https://www.youtube.com/watch?v=mDmDQm3152E',
  },
  {
    id: 'tall-kneeling-halo',
    name: 'Tall-kneeling halo',
    prescription: '5 / direction',
    mode: 'reps',
    cue: 'Circle close around your head while keeping your ribs down and neck relaxed.',
    tags: ['Shoulder mobility', 'Upper back'],
    media: '/media/tall-kneeling-halo.gif',
    source: 'https://www.youtube.com/watch?v=0esYCS6dFQk',
  },
  {
    id: 'tall-kneeling-chop',
    name: 'Tall-kneeling chop',
    prescription: '6–8 / side',
    mode: 'reps',
    cue: 'Move the bell diagonally across your body. Rotate through your upper back while keeping your hips controlled.',
    tags: ['Rotation', 'Obliques'],
    media: '/media/tall-kneeling-chop.gif',
    source: 'https://www.youtube.com/watch?v=BslVJKQXlcQ',
  },
  {
    id: 'half-kneeling-rotational-press',
    name: 'Half-kneeling rotational press',
    prescription: '6 / side',
    mode: 'reps',
    cue: 'Start light. Rotate smoothly through your torso and finish with the bell controlled overhead—never force the range.',
    tags: ['Shoulders', 'Rotation'],
    media: '/media/half-kneeling-rotational-press.gif',
    source: 'https://www.youtube.com/watch?v=9tbeLypLKHg',
  },
  {
    id: 'kettlebell-windmill',
    name: 'Kettlebell windmill',
    prescription: '5–6 / side',
    mode: 'reps',
    cue: 'Hold the bell overhead with a locked arm. Push your hip sideways, keep a long spine and watch the bell.',
    tags: ['Rotation', 'Shoulder stability'],
    media: '/media/kettlebell-windmill.gif',
    source: 'https://www.youtube.com/watch?v=MP9GRrr18Yc',
  },
  {
    id: 'figure-eight-to-hold',
    name: 'Figure-eight to hold',
    prescription: '6 / direction',
    mode: 'reps',
    cue: 'Pass the bell behind one leg and receive it securely at chest height. Stay smooth rather than rushing.',
    tags: ['Coordination', 'Rotation'],
    media: '/media/figure-eight-to-hold.gif',
    source: 'https://www.youtube.com/watch?v=ukc7kuFBlGY',
  },
  {
    id: 'around-the-body-pass',
    name: 'Around-the-body pass',
    prescription: '20–30 sec / direction',
    mode: 'duration',
    targetDuration: 20,
    cue: 'Pass the bell close around your body, receive it at shoulder height and pause before the next circle.',
    tags: ['Shoulders', 'Anti-rotation'],
    media: '/media/around-the-body-pass.gif',
    source: 'https://www.youtube.com/watch?v=nj26JAvAl-U',
  },
]

export const workouts = [
  {
    id: 'workout-a',
    label: 'A',
    name: 'Back & shoulder strength',
    note: 'Complete 2–3 sets. Rest 60–90 seconds between sets.',
    exerciseIds: exercises.slice(0, 6).map(({ id }) => id),
  },
  {
    id: 'workout-b',
    label: 'B',
    name: 'Rotation & resilient shoulders',
    note: 'Complete 2–3 controlled rounds. Accuracy matters more than speed.',
    exerciseIds: exercises.slice(6).map(({ id }) => id),
  },
]
